### ISSUE TITLE
TCP/IP Disconnect Notification

### ISSUE THREAD

**Issue by Satheesh-satz** [Beckhoff/ADS#10]
Hi Sven,

Is there a way to get a disconnect event notification from the ADS Library in case of any network connection loss or manual network disconnect from the PLC (CX hardware) ?

or

Do we need to have our own keep alive packet transaction with the PLC?

**Comment by soberschmidt** [comment]
ADS do not provide a heartbeat. Your client should handle it by checking the state of PLC or Systemservice (Port 10000) and the symbolversion of your PLC  to detect OnlineChanges.

Indexgroup 0xF008 
Offset 0 
Length 1
