### ISSUE TITLE
ADS-State Notification invalid value

### ISSUE THREAD

**Issue by mriepl** [Beckhoff/ADS#108]
Hi,

if i add a notification to the ads-state:
![image](https://user-images.githubusercontent.com/26095455/73396769-60112580-42e2-11ea-8f5d-fdc5bf3ebbd4.png)
i get the notification and an handle (see line 1):
![image](https://user-images.githubusercontent.com/26095455/73396832-7d45f400-42e2-11ea-91fa-4ee4d96d207b.png)

I also received the initial notification after the add call.
In the notification header i received  this:
![image](https://user-images.githubusercontent.com/26095455/73397259-6653d180-42e3-11ea-9a70-f60d7f189c78.png)

The given value seems to be wrong.
With the TcAdsDll everything work fine.

**Comment by pbruenn** [comment]
Do you use the TcAdsDll header? It might be related to issue #12 .
See my old [comment](https://github.com/Beckhoff/ADS/issues/12#issuecomment-148304863) for details.
If you want to use the same header, you can try a patch like this:
https://github.com/dabrowne/ADS/commit/e181ca260d5cdcdd7afc4bf07c80393f4ce96ddc

**Comment by mriepl** [comment]
In my wrapper i have added to the struct AdsNotificationHeader the entry "data[ANYSIZE_ARRAY]" like TcAdsDll.

The problem was that the  notification datas was copied after the entry "data[ANYSIZE_ARRAY]" because in the marked line you want to jump to the data section of the callback with pointer arithmetic.

![image](https://user-images.githubusercontent.com/26095455/73640394-74507c00-466e-11ea-9ae0-7b7db69dd8f4.png)
