### ISSUE TITLE
Heap Corruption on AdsDelete

### ISSUE THREAD

**Issue by mriepl** [Beckhoff/ADS#109]
Hello,

when i call the AdsSyncDelDeviceNotificaton my heap crashes, any ideas?

![image](https://user-images.githubusercontent.com/26095455/73397592-2a6d3c00-42e4-11ea-8a8a-0eb88ddbf03a.png)

![image](https://user-images.githubusercontent.com/26095455/73397618-3953ee80-42e4-11ea-9719-490a9741e47d.png)

with the TcAdsDll everything is fine!

**Comment by pbruenn** [comment]
Do you have a small example to reproduce?

**Comment by mriepl** [comment]
i have called the callbackfunction with the wrong calling convention.
AdsLib: without
TcAdsDll: __stdcall
