### ISSUE TITLE
Win32 Error Code

### ISSUE THREAD

**Issue by Satheesh-satz** [Beckhoff/ADS#11]
Hi Sven,

Are we following the same win32 error codes in the ADS Library for the Network and other related issues 

For Example:

0x274c	10060	A socket operation was attempted to an unreachable host	
                                Host unreachable	Check network connection via ping

**Comment by pbruenn** [comment]
In general we try to keep all error codes consistent. Operating system (OS) specific errors will depend on your OS.
Let us know, if you discover a missmatch
