### ISSUE TITLE
Adding route to BC9050

### ISSUE THREAD

**Issue by kapperi** [Beckhoff/ADS#116]
Hi,

I have linux client working on 192.168.1.18 and .1.1 and twincat running in 192.168.1.22 and .1.1

Bc9050 running in 192.168.1.20 and .1.1.

Where and how do I add route from 192.168.1.18 to PLC 192.168.1.20.

Windows side is easy, just to add route with router but I cant add linux machine to route anywhere.

**Comment by soberschmidt** [comment]
Hi,
BC9050 bus couplers won't need a route to accept the communication.
BR Sven

**Comment by kapperi** [comment]
Ok,

Thank you for information.
