### ISSUE TITLE
Add an example to read WSTRING with OOI

### ISSUE THREAD

**Issue by Frants1987** [Beckhoff/ADS#122]
Hello,
I started to build an application using the OOI version of the lib. However, I'm missing an example on how to read strings / wstrings from TwinCAT.
I tried using:
-  `AdsVariable<std::string>` which gave me nothing useful since the string has no defined size
-  `AdsVariable<std::array<char, 80>>` which wasn't helpful either
Could anyone point me in the right direction on how to use this class?
Thanks

**Comment by Frants1987** [comment]
OK, I got it to work with `AdsVariable<std::array<unsigned short, 80>>` but please point me to a better solution if there is one.
Btw. thanks for making the code available to the public.

**Comment by pbruenn** [comment]
I don't know any better solution. This might be helpful:
```
using WSTRING = std::array<uint16_t, 80>;
AdsVariable<WSTRING> var;

```
