### ISSUE TITLE
how to know if a variable is persistent or not?

### ISSUE THREAD

**Issue by chrisbeardy** [Beckhoff/ADS#137]
Hi, 

I have this example from the website https://infosys.beckhoff.com/english.php?content=../content/1033/tcsample_vc/html/tcadsdll_api_cpp_sample10.htm&id=1091195345805397691

which lets you read the follwing info:
![image](https://user-images.githubusercontent.com/20585410/112481503-fae28400-8d6e-11eb-8c8e-2d67c6aecd7e.png)

Is there a way of getting more information on the variable? I would like to know if a variable is declared as Persistent or Retentive?

e.g.

```
VAR PERSISTENT
   var: BOOL;
END_VAR
```

**Comment by heppth** [comment]
Hi chris,

have a look at `AdsSymbolEntry.flags`. You are looking for `Persistent = 256u` and `PersistantDatatype = 2097152u,`
I hope this helps you.
