### ISSUE TITLE
OSError: adslib.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by goodmail126** [Beckhoff/ADS#143]
![snipaste_20210515_143012](https://user-images.githubusercontent.com/40396204/118353241-f92b8480-b597-11eb-811f-3f843aa7142d.jpg)

[pyads3.3.5]
I guess some files were missing...

**Comment by pbruenn** [comment]
This is the wrong project. You might want to ask here: https://github.com/stlehmann/pyads

**Comment by pbruenn** [comment]
Here is your bug fixed: https://github.com/stlehmann/pyads/issues/185
