### ISSUE TITLE
Notification example does not report updated values

### ISSUE THREAD

**Issue by towillem** [Beckhoff/ADS#15]
I'm testing the notification mechanism from the ADS protocol using the AdsSyncAddDeviceNotificationReqEx call.
The provided example has been build on Ubuntu 14.04 LTS and Windows7-64bit cygwin64.
On both platform the ADS client runs without errors.
The application data from the PLC-TestProject in the array is continously updated.
The reported value from the ADS client for indexgroup 0x4020 with offset 4 is always 0 on both plaforms, that is incorrect. Even with a sample size of 1, the byte value should be update conform the value in the array.
Check the attached screenshots of the PLC application and the reported output of the ADS clients on both platforms.
The screenshot of the About TwinCAT System is also attached.

![screenshot 2015-10-27 21 57 20](https://cloud.githubusercontent.com/assets/14979925/10775345/e2ed3cdc-7d07-11e5-9453-af1343a920ee.png)
![screenshot 2015-10-27 22 01 59](https://cloud.githubusercontent.com/assets/14979925/10775347/e2edbb08-7d07-11e5-86a5-21cb8dad7296.png)
![screenshot 2015-10-28 00 03 06](https://cloud.githubusercontent.com/assets/14979925/10775349/e2ef3a5a-7d07-11e5-8911-c2166f51a4ed.png)
![screenshot_windows7-64](https://cloud.githubusercontent.com/assets/14979925/10775348/e2eeae28-7d07-11e5-95ad-aa0d8e79bac2.PNG)
![ubuntu_14 04lts](https://cloud.githubusercontent.com/assets/14979925/10775346/e2edb1bc-7d07-11e5-8728-1c356f1118a3.png)

**Comment by soberschmidt** [comment]
Hi Ton,

please verify the adresses with our target browser (VS Menue/Scope/TargetBrowser). Furthermore provide WireShark Dump via Mail.

**Comment by Satheesh-satz** [comment]
Hi Sven,

I am seeing an error saying "Symbol could not be found" when i tried to open the either the "plcTask" or "Port_851" sub items listed on my system.

Could you please help me with that .

**Comment by towillem** [comment]
Hi Sven,

Yep that’s it, the address from the example is not in sync with the PLC Test project.
After updating the address in the example, the values are updated.

regards, Ton
