### ISSUE TITLE
Router CleanUp

### ISSUE THREAD

**Issue by RamJamGit** [Beckhoff/ADS#150]
Unfortunately, the Router->CleanUp function cannot be called via a high-level language (C++, C#) interface. Is there a possibility to initiate the Router->CleanUp via ADS?

![TC_Router_CleanUp](https://user-images.githubusercontent.com/66592136/132661824-ed23285f-705d-4797-b269-801513c36ed9.jpg)
![TC_Router_CleanUp-AdsViewer](https://user-images.githubusercontent.com/66592136/132661971-68ca54b5-7f87-4f64-8b9c-31ea59f1ab70.jpg)

**Comment by RamJamGit** [comment]
@soberschmidt The Router->CleanUp should be executed locally and the tray menu, which contains the menu item, is deactivated. In the case of terminated processes (crash) under TwinCAT 2, the CleanUp is used to close the ADS connections that can no longer be used by the router. As a result, the crashed process (zombie process) is separated from TwinCAT and can then also be terminated.

**Comment by soberschmidt** [comment]
@RamJamGit This issue is not related to the open source ads client of this repo. Please contact support@beckhoff.com
