### ISSUE TITLE
Unable to read data from Beckhoff BK9050 TCP/IP bus coupler

### ISSUE THREAD

**Issue by Rajesh-VR** [Beckhoff/ADS#153]
Hi All,

We have a Beckhoff BK9050 TCP/IP bus coupler with five input channels (KL1114) and three output channels (KL2134). We downloaded the sample code from "https://github.com/Beckhoff/ADS/blob/master/example/example.cpp" and tried to run "readExample" method with gcc 9.3.0, then we are getting this output (port: 851, group: 0x4020):

**2021-10-28T14:17:49+0200 Info: Connected to 192.168.1.237
readExample():
ADS read 2021-10-28T14:17:49+0200 Info: connection closed by remote
Error: 6
AdsException message: Ads operation failed with error code 6.
Hit ENTER to continue**

Then we tried to run the "readExample" method with port '300', then getting this output (port: 300, group: 0x4020):

**2021-10-28T14:15:39+0200 Info: Connected to 192.168.1.237
readExample():
ADS read 2021-10-28T14:15:44+0200 Error: select() timeout
2021-10-28T14:15:44+0200 Warning: InvokeId of response: 0 timed out
2021-10-28T14:15:44+0200 Info: connection closed by remote
Error: 745
AdsException message: Ads operation failed with error code 1861.
Hit ENTER to continue**

We used the port (301), group (0xF031) and offset values detected by the Twincat System Manager for that specific terminal and channel, but nothing works. So we are requesting technical support for solving this issue.
checked #14 already.

Thanks,
Rajesh

@pbruenn  @0xQSL @soberschmidt

**Comment by pbruenn** [comment]
I guess this was solved on a sidechannel? If now feel free to reopen.
