### ISSUE TITLE
Warning: No dispatcher found for notification

### ISSUE THREAD

**Issue by Summerxiaxia623** [Beckhoff/ADS#162]
I wrote a program to read PLC temperature sensors every 1 second. I use sleep(1) after each reading. However, the warning: No dispatcher found for notification will show up after each reading and the TwinCat program will stopped running after some readings and saying couldn't scan target.

**Comment by pbruenn** [comment]
See:
https://github.com/Beckhoff/ADS/issues/74#issuecomment-424376009
https://github.com/Beckhoff/ADS/issues/85#issuecomment-486726003
