### ISSUE TITLE
How to install ADS on FreeBSD 13

### ISSUE THREAD

**Issue by luciovalentini** [Beckhoff/ADS#168]
Could you please add instructions to install ADS in FreeBSD 13?
Thank you.

**Comment by luciovalentini** [comment]
OSError: Shared object "libTcAdsDll.so" not found

**Comment by pbruenn** [comment]
Sorry I don't know what you are doing. I just pulled https://download.freebsd.org/ftp/releases/CI-IMAGES/13.1-RELEASE/amd64/Latest/FreeBSD-13.1-RELEASE-amd64-BASIC-CI.raw.xz

Unzipped and ran it.
Then inside of the vm the README instructions worked just like expected. All I had to do is `pkg install git meson`

Even the example just works. So your error message states libTcAdsDll. From that I can only guess, that you are trying to pass extra arguments to meson.
