### ISSUE TITLE
What is the latest version?

### ISSUE THREAD

**Issue by hellozee** [Beckhoff/ADS#178]
I see in the commits the latest version is 0.0.16 but the tags only exist till 0.0.14. Does that mean some stuff after 0.0.14 may not work?

**Comment by pbruenn** [comment]
Well, we keep the master stable so you should be safe to always use latest git.
Sometimes we package the library into an Debian package, only then we  introduce a "version".

As this confused at least you, I pushed a tag for that last Debian version bump. But it is really meaningless.

**Comment by hellozee** [comment]
thanks, 😄
