### ISSUE TITLE
Class "AdsDevice" has no member "GetDeviceAdsVariables" and Undefined identifier "IAdsVariable"

### ISSUE THREAD

**Issue by yudonghou123** [Beckhoff/ADS#184]
Hi,my system is ubuntu22.04,When I use the ADS recommended combination with ROS when migrating it to ROS2, the terminal always reports that Class "AdsDevice" has no member "GetDeviceAdsVariables" and Undefined identifier "IAdsVariable",how to solve it

**Comment by pbruenn** [comment]
Sounds like you are using the fork based on https://github.com/Beckhoff/ADS/pull/170. The quality of that PR doesn't convince me to pull it, so you should ask your questions in their fork: https://github.com/Capacites/ADS
