### ISSUE TITLE
ADS TwinCAT3 And Linux Virtual Machine Communication : Error: 1861

### ISSUE THREAD

**Issue by ismailalhajosman** [Beckhoff/ADS#193]
Hello, 

I have my TwinCAT3 running on Winodws 10 and want to communicate with Linux OS running on Oracle Virtual Machine. I followed all the steps written in the [readme](https://github.com/Beckhoff/ADS#readme) and run example.cpp file to do the communication however I get this error. I followed all issues related to this problem including #14 and #56  but could not solve this error.

This is my part of the code to assign PLC  remote IP :
![code1](https://user-images.githubusercontent.com/76249138/224023837-aaaf38e9-8756-48e9-9c46-4dc68acbe643.jpg)

And this my PLC IP and Router settings : 
![static router1](https://user-images.githubusercontent.com/76249138/224023976-895d98ec-eaaf-4b3e-adfd-e8e6f87992d1.jpg)

Here is the error I am getting: 
![error1](https://user-images.githubusercontent.com/76249138/224025531-ba68c05e-ff78-4df4-918b-7eb13d12d92a.jpg)

Any help ? 

Thanks in advance !

**Comment by pbruenn** [comment]
I assume N_V_M is you Linux virtual machine and the Static Routes screenshot is from the Windows host?

In that case the AdsSetLocalAddress is wrong.  Your route is configured for 192.168.108.212.1.1, but your AdsSetLocalAddress() uses 192.168.0.114.1.1

**Comment by ismailalhajosman** [comment]
Yes that is correct.

The problem is solved my changing  my AdsSetLocalAddress() to 192.168.108.212.1.1 

Thanks a lot!
