### ISSUE TITLE
How to Dynamically Read Struct Symbols and Obtain Subsymbol Values Using the Beckhoff ADS Library in C#

### ISSUE THREAD

**Issue by jganitzer** [Beckhoff/ADS#198]
Hello,

I am currently using the Beckhoff ADS library in my C# project and would like to read a struct symbol. My goal is to convert the byte array value of the symbol dynamically at runtime, and retrieve the values of the subsymbols without defining the memory layout of the struct type in the C# code.

Is it possible to achieve this using the Beckhoff ADS library? If so, could you please provide me with some guidance or resources on how to accomplish this?

Thank you for your time and assistance.

**Comment by pbruenn** [comment]
Beckhoffs ADS .NET documentation is here: https://infosys.beckhoff.com/content/1033/tc3_ads.net/9407515403.html?id=6770980177009971601
