### ISSUE TITLE
CMake Error at CMakeLists.txt:40 (install): install TARGETS given target "ads" which does not exist in this directory.

### ISSUE THREAD

**Issue by IricEmage** [Beckhoff/ADS#207]
I build the ADS library with follow command: 
+ git clone https://github.com/Beckhoff/ADS.git
+ cd ADS/
+ mkdir build && cd build
+ cmake ..
+ cmake --build .
+ cmake --install. 

But in step _**cmake ..**_, I got this error.
OS: Jetson xavier AGX 32G

**Comment by simonschmeisser** [comment]
I get the same error when trying to build via `add_subdirectory(ADS)` but not when I try to build standalone as you described above

**Comment by simonschmeisser** [comment]
Seems to require CMake 3.13: https://stackoverflow.com/questions/34443128/cmake-install-targets-in-subdirectories

**Comment by IricEmage** [comment]
Thank you, update CMake  3.20 to slove it.
