### ISSUE TITLE
How to Write 2D Array of Struct through ADS?

### ISSUE THREAD

**Issue by dzhydaniel** [Beckhoff/ADS#232]
![image](https://github.com/user-attachments/assets/86136872-408d-4cf2-b88e-58457c00720f)
![image](https://github.com/user-attachments/assets/c11782a5-152c-465d-b6b3-fb8252bd4c2f)
![image](https://github.com/user-attachments/assets/bb59f97b-87f2-40ac-bbef-516b029e7747)

I have a Struct and described with    [StructLayout(LayoutKind.Sequential, Pack = 1)] , and i have a  2d array type of the struct, when use ReadAny it's fine , but when i try to write the array back with WriteAny it comes back with unable to marshal issue.
Does any one know how to write 2d array with struct elements?

**Comment by pbruenn** [comment]
It seems you are in the wrong repository. This one is the open source c++ standalone library. Your screenshots look like .NET. Please, contact the support for the .NET library you use

**Comment by dzhydaniel** [comment]
I figured it out, just transformed 2D array to 1D array, it will work.
