### ISSUE TITLE
Incorrect GitHub repository link for Beckhoff.TwinCAT.Ads NuGet package version 4.4.37

### ISSUE THREAD

**Issue by ClaudiusR** [Beckhoff/ADS#241]
Hi everyone,

I was directed via the license link from this nuget https://www.nuget.org/packages/Beckhoff.TwinCAT.Ads/4.4.37 to this repository. But I think it does not points to the correct repo, or am I wrong. I cannot find a tag / release that would match the 4.4.37 version.

**Comment by pbruenn** [comment]
No you are right, this is the wrong repository. This repository is about an OpenSource C++ Version.

You can contact the owners of the NuGet package here: https://www.nuget.org/packages/Beckhoff.TwinCAT.Ads/4.4.37/ContactOwners
