### ISSUE TITLE
Suggestion: Add additional interfaces to the library

### ISSUE THREAD

**Issue by xift** [Beckhoff/ADS#26]
Hi,
thanks for making this open source. I work with TwinCAT daily and was happy to see some of the implementation. The library code is pretty clean as well. Nice work!

So my suggestion would be to build upon this library and add interfaces.
Something that comes to mind is a class based interface for C++ which uses templates to enable compile time type checks for the read and write functions. Or a Matlab file which provides wrapper methods. 
I know there are Matlab examples and things like pyAds. However, I'd like to see it bundled in one repository.

Regards 
Michael

**Comment by pbruenn** [comment]
Hi Michael,
yes I think it's a good idea to extend this lib with an object oriented interface. What's holding me from doing it, is my lack of a concrete use case. I don't want to implement something without a prove of it's real usage.
So my suggestion would be, implement it on a branch of your forked repository and let us know. Then we have a base on which we can discuss the integration into upstream.

Best regards,
Patrick

**Comment by xift** [comment]
I agree that there probably is no real use case for Beckhoff in a new interface. 
However, the API is a bit old-fashioned and uncomfortable to use (Handle here, error code there, ...). 
I accept the challenge and see what I can do. I actually stumbled upon this repository when looking for a side-project that might be beneficial at work. So this might be a perfect opportunity.

Michael

**Comment by xift** [comment]
Gave it a shot...
#35
