### ISSUE TITLE
dev-ooi: Handles currently can "outlive" the global AmsRouter object

### ISSUE THREAD

**Issue by xift** [Beckhoff/ADS#41]
Hi, 

I'm currently working on the ooi branch and its looking good so far.
However, there is a problem with the HandleGuard and the HandleDeleter functor.
HandleDeleter::() uses the global AmsRouter object to delete the handle. 
However, in the "relatively special" case that an AdsVariable object is global and outlives the router we currently run into an exception.

The Construct On First Use Idiom would probably solve this. 

Regards 
Michael

**Comment by pbruenn** [comment]
Hi Michael,
thank's for testing, I try to look into this until end of this week.
Regards, Patrick

**Comment by pbruenn** [comment]
Okay I meant end of this week ;-).
