### ISSUE TITLE
Problem with routes in TwinCAT

### ISSUE THREAD

**Issue by chrizzly123** [Beckhoff/ADS#44]
Hi,
i just tried the new function AdsSetLocalAdress(). I tested the endings ...1.1 and ...1.2. For that, I added two routes in TwinCAT, as you can see on the picture:

![grafik](https://cloud.githubusercontent.com/assets/24834128/25489509/56b32d5e-2b6a-11e7-8964-701420ebfbbf.png)

When i then started to test, only ...1.1 worked, while ...1.2 didnt receive any responses from TwinCAT. Then i deleted the ...1.1 route in TwinCAT, and the ...1.2 route started to work. After that, i added the ...1.1 route again. Now ....1.2 was on top of ...1.1, and ...1.2 still worked while ...1.1 didnt. So it seems like only the upper route works, while the others are getting ignored. I also used Wireshark, for the second route there are no responses. 
Is it supposed to work like this?
TwinCAT Version is 3.1.4020.

Thanks,
Chris

**Comment by pbruenn** [comment]
Hi Chris,
unfortunately yes it is supposed like that. TwinCAT on Windows (not WinCE) seems unable use SubRoutes. On a WinCE TwinCAT it should work just fine. I'm not an expert on TwinCAT but  @soberschmidt or our official Beckhoff support can help you better on this.

Best Regards,
Patrick
