### ISSUE TITLE
AdsLib crashes when receiving notifications from older versions of Twincat2

### ISSUE THREAD

**Issue by kirlek** [Beckhoff/ADS#50]
Please see original issue here: MrLeeh/pyads/issues/38

Wireshark capture of ADS traffic causing crash:
[pyads_tc2_rberror.zip](https://github.com/Beckhoff/ADS/files/1381551/pyads_tc2_rberror.zip)

**Comment by pbruenn** [comment]
fixed by 82e2ecf052bbaa1d7c1e530eb8a16f4c592b69b4
