### ISSUE TITLE
make install failing

### ISSUE THREAD

**Issue by davidAlittle** [Beckhoff/ADS#51]
Following readme:
:~/ADS$ make install
make: *** No rule to make target 'install'.  Stop.

Fresh Ubuntu 17.04 install. 

/edit/ I see the note on the most recent change to Makefile says "remove install, use lib directly". Can you please update the readme to reflect the new steps? Not sure what needs to go where to use directly.

**Comment by pbruenn** [comment]
Yes, you are right. The 'make install' step is gone, now.
It was used to copy the build library to the example application sub directory. That was changed in favor to add the correct include and library path in the example. See the example/Makefile for details.
README got updated by 7df1d60f8bf088a2be718323d27aa2156f7d7b0f
