### ISSUE TITLE
AdsAmsRegisterRouterNotification, AdsAmsUnRegisterRouterNotification

### ISSUE THREAD

**Issue by rhythmchicago** [Beckhoff/ADS#52]
Hello. I use TwinCAT3 on Windows regularly and use AdsAmsRegisterRouterNotification and AdsAmsUnRegisterRouterNotification to detect changes in the router (AMSEVENT_ROUTERSTOP, AMSEVENT_ROUTERSTART, AMSEVENT_ROUTERREMOVED). I've been using this library to port the program I wrote to other operating systems, but can't find an replacement for these functions. Is there a way of detecting changes in the remote router state using this library?

Thanks!

**Comment by soberschmidt** [comment]
Hi, please check the C++ samples of the official TcAdsDll of Beckhoff: https://infosys.beckhoff.com/index.php?content=../content/1031/tc3_adssamples_c/html/tcadsdll_api_cpp_sample11.htm&id=1738474616755725428
The header files can be found in every TwinCAT-Installation under c:\TwinCAT\AdsApi

Best Regards,
Sven
