### ISSUE TITLE
Beckhoff ADS

### ISSUE THREAD

**Issue by jeroen54** [Beckhoff/ADS#55]
How do i get the Beckhoff ADS component working in homeassistant on a PI3 ?
I added the component and getan error.
I know al lot about Beckhoff TwinCat2 and 3

**Comment by pbruenn** [comment]
You just posted to the bug tracker of AdsLib a low level library (as far as I know) used by the home-assistant component.
If you need help with home-assistant please look at:
https://home-assistant.io/help/
Make sure to be more specific when you describe your issue there. Without any details about your error, they wouldn't be able to help you.
