### ISSUE TITLE
"make test" Error on macOS 10.13.3

### ISSUE THREAD

**Issue by Loop-Design** [Beckhoff/ADS#58]
on "make test" I get an error:
c++ AdsLibTest/main.cpp AdsLib-Darwin.a -lpthread -lc++ -I AdsLib/ -I tools/ -std=c++11 -pedantic -Wall  -o AdsLibTest.bin
AdsLibTest/main.cpp:9:10: fatal error: 'fructose/fructose.h' file not found
#include <fructose/fructose.h>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [AdsLibTest.bin] Error 1

**Comment by pbruenn** [comment]
If you want to run the test suite you need to get the FRUCTOSE C++ Unit Test Framework.
Run or see [tools/10_get_fructose](https://github.com/Beckhoff/ADS/blob/cdf679f/tools/10_get_fructose.sh) to install it (a few header files).
To run this tests you need a very specific setup. PLC-TestProject running on a PC with hostname ads-server.
If all you want is a small tests to see if your setup is working, try the example/.
