### ISSUE TITLE
Does anybody have .pdf file for ADS specification?

### ISSUE THREAD

**Issue by lianhub** [Beckhoff/ADS#59]
As I remembered, there is .pdf file for ADS specification, which can be downloaded from somewhere.
* But I googled, and found nothing.

So weird, I thought I downloaded this file before, but could not find it in my computer either!
* Maybe something wrong with my memory?            (but I remembered it so vividly!) 

Thanks,
Jerry

**Comment by Beckdthompson** [comment]
https://infosys.beckhoff.com/content/1033/tc3_adscommon/html/tcadsamsspec_amstcppackage.htm?id=959197645592921229
