### ISSUE TITLE
 A bug? (m_SockAddress.sin_port = 703, shouldn't it be 48898?)

### ISSUE THREAD

**Issue by lianhub** [Beckhoff/ADS#61]
I think I may find a bug:
* I modified **Sockets.cpp** to print the port number:
```
uint32_t TcpSocket::Connect() const
{
    const uint32_t addr = ntohl(m_SockAddress.sin_addr.s_addr);

+   printf("The IP address is: %s      Port: %d\n", inet_ntoa(m_SockAddress.sin_addr), m_SockAddress.sin_port);

    if (::connect(m_Socket, reinterpret_cast<const sockaddr*>(&m_SockAddress), sizeof(m_SockAddress))) {
        LOG_ERROR("Connect TCP socket failed with: " << WSAGetLastError());
        return 0;
    }
   ...
}
```
* then I got:
```
debian@beaglebone:~/ADS/example$ make test
./example.bin
The IP address is: 192.168.2.41      Port: 703
     (after a couple of minutes)
2018-03-19T21:34:43+0000 Error: Connect TCP socket failed with: 110
Adding ADS route failed, did you specified valid addresses?
```

Shouldn't the port be **48898**?
Anybody can confirm my conclusion? or maybe I am wrong?

Thanks,
Jerry

**Comment by pbruenn** [comment]
Unfortunately that's no bug. sin_port is in "network byteorder/big endian" so you would have to convert it back into host byteorder with ntohs() and will see it is correct.
You could use Wireshark[[1](https://www.wireshark.org)] to see the packet on wire (in network byte order, but wireshark will decode correctly).

[1] https://www.wireshark.org

**Comment by lianhub** [comment]
OK, I see the logic!
Thanks Pbruenn, so this issue can be closed now!
