### ISSUE TITLE
Create handle failed with: 0x745 (1861)

### ISSUE THREAD

**Issue by henryzixuan** [Beckhoff/ADS#68]
I am trying to run the example.cpp provided by the repository on beagle bone black, where Linux is installed. But I get the error code 0x745 (1861). As far as I understand, this repository is used to communicate with Beckhoff device through ADS without TwinCat installed. All I need is to add a route before I start communicating. But how can I add a route without TwinCat installed on my Linux?

Thanks a lot!
Henry

**Comment by pbruenn** [comment]
For details please read my responses to #14. Here is a short summary:
1. Make sure to assign a deterministic AmsNetId on your AdsLib client -> AdsSetLocalAddress()
2. In your AdsLib client add a route to your TwinCAT system -> AdsAddRoute()
3. On your TwinCAT system add a route for your AdsLib client
