### ISSUE TITLE
Error 1861- tried AdsSetLocalAddress

### ISSUE THREAD

**Issue by reyanvaldes** [Beckhoff/ADS#69]
Hi Sven or support,
First of all, this is nice library,  very good work!.

I am facing some challenges that has been reported before regarding the error 1861, but the solution recommended didn't work for me. We disable firewalls, can ping PLC (TwinCAT 3), checking the static routing on PLC, it is defined. We can connect to PLC, but when try to read got the error 1861. We follow same as shown on example, adding routing and open port. We have tried several things, including using the AdsSetLocalAddress calling before adding routing with AdsAddRoute that was recommended to fix this issue but no success. We are using Debian Jessie O.S.

Please can you help us how to troubleshooting?

Does the library support some kind of debug mode for troubleshooting? What else we can check?
 
Note: If we use a VM with Kepware, it can read fine the tags.

Thanks a lot for any recommendation
Reyan

**Comment by pbruenn** [comment]
Hi Reyan,
sorry for the late response, I am just back from vacation.
Did you solve the issue in the meantime?
If not, my only idea is to take a look on a Wireshark capture, made between your PLC and Debian.
Regards,
Patrick
