### ISSUE TITLE
Which port to connect

### ISSUE THREAD

**Issue by delarosa1962** [Beckhoff/ADS#7]
We are developing a driver -- we see port 851, but also see port  AMSPORT_R0_PLC_RTS1
What is the difference? I see in the h files --- RTS1, 2, 3 and RTS4. Which one should we use ?
Is this fixed in the PLC ?

**Comment by soberschmidt** [comment]
TwinCAT3 uses Port 851. RTS1...4 are used for TwinCAT2 PLC's
