### ISSUE TITLE
Error--Add device notification failed with: 1861

### ISSUE THREAD

**Issue by xuyuan25** [Beckhoff/ADS#71]
Hi support,
  i want to use your code connect beckhoff PLC(twincat2,winCE) on linux without twincat.i edit example.cpp like this:
![image](https://user-images.githubusercontent.com/34471929/42806809-d906ce06-89e1-11e8-80c6-4067b286d1a0.png)
  there are some error like this:
![image](https://user-images.githubusercontent.com/34471929/42807210-c6634044-89e2-11e8-8cbc-0af1c697ed32.png)
 thanks a lot for your recommendation!
Yuan

**Comment by pbruenn** [comment]
On your TwinCAT2 system, did you add a route for your Linux system with AmsNetId "5.21.95.61.1.1"?

**Comment by xuyuan25** [comment]
thank you for your answer
now I add a route with AmsNetID"5.21.95.61.1.1" on TwinCAT2 system,and still has error:
 
![image](https://user-images.githubusercontent.com/34471929/42813893-0ba6df28-89f5-11e8-8d96-ce99f85f50ec.png)
thanks a lot for your recommendation!
Yuan

**Comment by xuyuan25** [comment]
hi,Patrick
i have solve this error by change the port,so i can read something.
thanks.

Now,I'm try to write something into beckhoff PLC.I find some example from https://infosys.beckhoff.com/english.php?content=../content/1033/tcsample_vc/html/tcadsdll_api_cpp_sample17.htm&id=20654114132734386906 so I edit code and there are no error, but beckhoff cannot received what i write.
if you have suggestion or example，you can tell me.
 thanks a lot for your recommendation.
yuan

**Comment by pbruenn** [comment]
If I understand correctly `AdsSyncReadReqEx2()` is working, now.
I would try these steps next:
1.Test if writing to the PLC is working with [`AdsSyncWriteReqEx2`](https://github.com/Beckhoff/ADS/blob/master/AdsLib/AdsLib.h#L145)
2. Test if the sum command is working, by using it to only read.
