### ISSUE TITLE
Checking if symbol table has changed

### ISSUE THREAD

**Issue by user500** [Beckhoff/ADS#90]
Hi,

I was wondering if there is a function that can be called to poll if the symbol table has changed as an alternative to using a callback?

Thank you,
Patrick

**Comment by soberschmidt** [comment]
Hi Patrick, 
you can register a notification or poll the online change counter, which will be incremented with every online change: TC3 symbol TwinCAT_SystemInfoVarList._AppInfo.OnlineChangeCnt.

If a new program is downloaded, the symbol version will be incremented. The symbol version can be polled by an AdsRead-Request to Indexgroup=0xF008 Offset=0 Bytelength=1.

Best Regards,
Sven

**Comment by user500** [comment]
Thank you!


-Patrick


________________________________
